/* eslint-disable no-restricted-globals */

import { clientsClaim, setCacheNameDetails } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';

// Claim clients that were connected to a previous version of the service worker.
clientsClaim();

// Configure the prefix and suffix for cache names.
setCacheNameDetails({
  prefix: 'issue-tracker',
  suffix: ''
});

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// Handle navigation, with client-side routing
registerRoute(new NavigationRoute(createHandlerBoundToURL('/index.html')));
